# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140212131424");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 295);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20140212131424");
user_pref("browser.startup.homepage_override.mstone", "27.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1394794899768");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1394708499768");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 267);
user_pref("datareporting.sessions.current.main", 29);
user_pref("datareporting.sessions.current.sessionRestored", 331);
user_pref("datareporting.sessions.current.startTime", "1394709629672");
user_pref("datareporting.sessions.current.totalTime", 6);
user_pref("datareporting.sessions.currentIndex", 12);
user_pref("datareporting.sessions.previous.0", "{\"s\":1394708499667,\"a\":2,\"t\":8,\"c\":true,\"m\":22,\"fp\":433,\"sr\":530}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1394708637963,\"a\":1,\"t\":4,\"c\":true,\"m\":23,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.10", "{\"s\":1394709151897,\"a\":5,\"t\":49,\"c\":true,\"m\":0,\"fp\":282,\"sr\":333}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1394709214092,\"a\":1,\"t\":2,\"c\":true,\"m\":24,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1394708643943,\"a\":1,\"t\":3,\"c\":true,\"m\":24,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1394708715011,\"a\":1,\"t\":1,\"c\":true,\"m\":24,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1394708737307,\"a\":1,\"t\":3,\"c\":true,\"m\":24,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1394708773590,\"a\":1,\"t\":1,\"c\":true,\"m\":33,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1394708781210,\"a\":1,\"t\":1,\"c\":true,\"m\":24,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1394708792232,\"a\":1,\"t\":1,\"c\":true,\"m\":27,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1394708946219,\"a\":1,\"t\":2,\"c\":true,\"m\":27,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1394709057935,\"a\":18,\"t\":88,\"c\":true,\"m\":25,\"fp\":285,\"sr\":345}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7B77d2ed30-4cd2-11e0-b8af-0800200c9a66%7D:9.5.4");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Users\\\\TheBlackRev\\\\Desktop\\\\App\\\\firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1394708480971,\"rdfTime\":1392244508000}}},{\"name\":\"app-profile\",\"addons\":{\"{77d2ed30-4cd2-11e0-b8af-0800200c9a66}\":{\"descriptor\":\"C:\\\\Users\\\\TheBlackRev\\\\Desktop\\\\Data\\\\profile\\\\extensions\\\\{77d2ed30-4cd2-11e0-b8af-0800200c9a66}\",\"mtime\":1394709145589,\"rdfTime\":1394709145579}}}]");
user_pref("extensions.lastAppVersion", "27.0.1");
user_pref("extensions.lastPlatformVersion", "27.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20140212131424");
user_pref("gecko.mstone", "27.0.1");
user_pref("general.skins.selectedSkin", "ftdeepdark");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1394709629);
user_pref("toolkit.telemetry.previousBuildID", "20140212131424");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1397300502);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
